Import the libraries

Load the data into the Python Notebook

In [1]:
import pandas as pd
january2013=pd.read_csv("data/yellow_tripdata_2013-01.csv")
"""
february2013=pd.read_csv("data/yellow_tripdata_2013-02.csv")
march2013=pd.read_csv("data/yellow_tripdata_2013-03.csv")
april2013=pd.read_csv("data/yellow_tripdata_2013-04.csv")
may2013=pd.read_csv("data/yellow_tripdata_2013-05.csv")
june2013=pd.read_csv("data/yellow_tripdata_2013-06.csv")
july2013=pd.read_csv("data/yellow_tripdata_2013-07.csv")
august2013=pd.read_csv("data/yellow_tripdata_2013-08.csv")
september2013=pd.read_csv("data/yellow_tripdata_2013-09.csv")
october2013=pd.read_csv("data/yellow_tripdata_2013-10.csv")
november2013=pd.read_csv("data/yellow_tripdata_2013-11.csv")
december2013=pd.read_csv("data/yellow_tripdata_2013-12.csv")
"""

'\nfebruary2013=pd.read_csv("data/yellow_tripdata_2013-02.csv")\nmarch2013=pd.read_csv("data/yellow_tripdata_2013-03.csv")\napril2013=pd.read_csv("data/yellow_tripdata_2013-04.csv")\nmay2013=pd.read_csv("data/yellow_tripdata_2013-05.csv")\njune2013=pd.read_csv("data/yellow_tripdata_2013-06.csv")\njuly2013=pd.read_csv("data/yellow_tripdata_2013-07.csv")\naugust2013=pd.read_csv("data/yellow_tripdata_2013-08.csv")\nseptember2013=pd.read_csv("data/yellow_tripdata_2013-09.csv")\noctober2013=pd.read_csv("data/yellow_tripdata_2013-10.csv")\nnovember2013=pd.read_csv("data/yellow_tripdata_2013-11.csv")\ndecember2013=pd.read_csv("data/yellow_tripdata_2013-12.csv")\n'

In [2]:
january2013.head(1)

,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,rate_code,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,surcharge,mta_tax,tip_amount,tolls_amount,total_amount
0,CMT,2013-01-01 15:11:48,2013-01-01 15:18:10,4,1.0,-73.978165,40.757977,1,N,-73.98984,40.751173,CSH,6.5,0.0,0.5,0.0,0.0,7.0

Getting the day of week for each row

We will be basing it on the pickup_datetime and adding it as a new column called weekday

0 = Monday

1 = Tuesday 

   ...
   
6 = Sunday

In [3]:
january_timestamp = pd.to_datetime(pd.Series(january2013['pickup_datetime']))
january_timestamp_array = []
for index in january_timestamp:
    january_timestamp_array.append(index.dayofweek)
january2013['weekday'] = january_timestamp_array
print("Finished January")

"""
february_timestamp = pd.to_datetime(pd.Series(february2013['pickup_datetime']))
february_timestamp_array = []
for index in february_timestamp:
    february_timestamp_array.append(index.dayofweek)
february2013['weekday'] = february_timestamp_array
print("Finished February")

march_timestamp = pd.to_datetime(pd.Series(march2013['pickup_datetime']))
march_timestamp_array = []
for index in march_timestamp:
    march_timestamp_array.append(index.dayofweek)
march2013['weekday'] = march_timestamp_array
print("Finished March")

april_timestamp = pd.to_datetime(pd.Series(april2013['pickup_datetime']))
april_timestamp_array = []
for index in apriltimestamp:
    april_timestamp_array.append(index.dayofweek)
april2013['weekday'] = april_timestamp_array
print("Finished April")
"""

Finished January

'\nfebruary_timestamp = pd.to_datetime(pd.Series(february2013[\'pickup_datetime\']))\nfebruary_timestamp_array = []\nfor index in february_timestamp:\n    february_timestamp_array.append(index.dayofweek)\nfebruary2013[\'weekday\'] = february_timestamp_array\nprint("Finished February")\n\nmarch_timestamp = pd.to_datetime(pd.Series(march2013[\'pickup_datetime\']))\nmarch_timestamp_array = []\nfor index in march_timestamp:\n    march_timestamp_array.append(index.dayofweek)\nmarch2013[\'weekday\'] = march_timestamp_array\nprint("Finished March")\n\napril_timestamp = pd.to_datetime(pd.Series(april2013[\'pickup_datetime\']))\napril_timestamp_array = []\nfor index in apriltimestamp:\n    april_timestamp_array.append(index.dayofweek)\napril2013[\'weekday\'] = april_timestamp_array\nprint("Finished April")\n'

In [76]:
january2013.head(10)
january2013.shape

(14776615, 19)

Subset by day of the week and verify the shapes to make sure its equal

In [93]:
january2013monday = pd.DataFrame(january2013)
january2013monday = january2013monday.loc[january2013monday['weekday'] == 0]
january2013monday.reset_index()

january2013tuesday = pd.DataFrame(january2013)
january2013tuesday = january2013tuesday.loc[january2013tuesday['weekday'] == 1]
january2013tuesday.reset_index()

january2013wednesday = pd.DataFrame(january2013)
january2013wednesday = january2013wednesday.loc[january2013wednesday['weekday'] == 2]
january2013wednesday.reset_index()

january2013thursday = pd.DataFrame(january2013)
january2013thursday = january2013thursday.loc[january2013thursday['weekday'] == 3]
january2013thursday.reset_index()

january2013friday = pd.DataFrame(january2013)
january2013friday = january2013friday.loc[january2013friday['weekday'] == 4]
january2013friday.reset_index()

january2013saturday = pd.DataFrame(january2013)
january2013saturday = january2013saturday.loc[january2013saturday['weekday'] == 5]
january2013saturday.reset_index()

january2013sunday = pd.DataFrame(january2013)
january2013sunday = january2013sunday.loc[january2013sunday['weekday'] == 6]
january2013sunday.reset_index()

,index,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,rate_code,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,surcharge,mta_tax,tip_amount,tolls_amount,total_amount,weekday
0,1,CMT,2013-01-06 00:18:35,2013-01-06 00:22:54,1,1.50,-74.006680,40.731781,1,N,-73.994499,40.750659,CSH,6.0,0.5,0.5,0.00,0.0,7.00,6
1,40,CMT,2013-01-06 00:46:25,2013-01-06 01:02:05,1,4.50,-73.991173,40.743129,1,N,-74.013761,40.702297,CSH,17.0,0.5,0.5,0.00,0.0,18.00,6
2,41,VTS,2013-01-13 10:13:00,2013-01-13 10:33:00,1,4.60,-73.915122,40.764012,1,NaN,-73.974220,40.760312,CRD,17.5,0.0,0.5,0.00,0.0,18.00,6
3,42,VTS,2013-01-13 10:20:00,2013-01-13 10:30:00,1,2.34,-73.990620,40.756457,1,NaN,-73.991502,40.739497,CSH,9.5,0.0,0.5,0.00,0.0,10.00,6
4,43,VTS,2013-01-13 10:23:00,2013-01-13 10:33:00,1,3.17,-73.975277,40.755822,1,NaN,-73.947255,40.793487,CSH,12.0,0.0,0.5,0.00,0.0,12.50,6
5,44,VTS,2013-01-13 10:29:00,2013-01-13 10:33:00,1,0.66,-74.007740,40.732270,1,NaN,-74.004190,40.737547,CSH,4.5,0.0,0.5,0.00,0.0,5.00,6
6,45,VTS,2013-01-13 10:27:00,2013-01-13 10:32:00,1,0.89,-73.982067,40.772542,1,NaN,-73.973927,40.778797,CSH,6.0,0.0,0.5,0.00,0.0,6.50,6
7,46,VTS,2013-01-13 10:27:00,2013-01-13 10:35:00,1,2.92,-73.992190,40.723945,1,NaN,-73.966325,40.715732,CRD,11.0,0.0,0.5,2.75,0.0,14.25,6
8,47,VTS,2013-01-13 10:27:00,2013-01-13 10:36:00,1,3.93,-73.982380,40.731427,1,NaN,-73.947020,40.779875,CRD,12.0,0.0,0.5,2.40,0.0,14.90,6
9,48,VTS,2013-01-13 10:33:00,2013-01-13 10:37:00,1,0.72,-73.982827,40.764125,1,NaN,-73.973905,40.756852,CSH,4.5,0.0,0.5,0.00,0.0,5.00,6
10,49,VTS,2013-01-13 10:29:00,2013-01-13 10:39:00,3,4.51,-73.957385,40.777180,1,NaN,-73.975322,40.729242,CRD,14.5,0.0,0.5,2.90,0.0,17.90,6
11,50,VTS,2013-01-13 10:25:00,2013-01-13 10:32:00,6,1.84,-74.008250,40.705572,1,NaN,-74.013047,40.716052,CRD,8.5,0.0,0.5,1.70,0.0,10.70,6
12,51,VTS,2013-01-13 10:27:00,2013-01-13 10:36:00,1,1.49,-73.996675,40.693190,1,NaN,-73.977798,40.684187,CSH,8.0,0.0,0.5,0.00,0.0,8.50,6
13,52,VTS,2013-01-13 10:32:00,2013-01-13 10:38:00,1,0.92,-73.956530,40.778727,1,NaN,-73.952395,40.786940,CSH,6.0,0.0,0.5,0.00,0.0,6.50,6
14,53,VTS,2013-01-13 10:33:00,2013-01-13 10:38:00,5,1.08,-73.997175,40.721965,1,NaN,-73.991078,40.733737,CSH,6.0,0.0,0.5,0.00,0.0,6.50,6
15,54,VTS,2013-01-13 10:02:00,2013-01-13 10:38:00,1,20.78,-73.788310,40.641513,2,NaN,-73.975515,40.792112,CRD,52.0,0.0,0.5,7.70,4.8,65.00,6
16,55,VTS,2013-01-13 10:07:00,2013-01-13 10:37:00,1,7.05,-73.999035,40.672960,1,NaN,-73.973943,40.753550,CRD,24.5,0.0,0.5,2.50,0.0,27.50,6
17,56,VTS,2013-01-13 10:33:00,2013-01-13 10:36:00,6,0.69,-73.962653,40.770742,1,NaN,-73.956623,40.775222,CRD,5.0,0.0,0.5,1.00,0.0,6.50,6
18,57,VTS,2013-01-13 10:32:00,2013-01-13 10:38:00,5,1.29,-74.006815,40.735370,1,NaN,-73.994637,40.749495,CRD,6.5,0.0,0.5,1.00,0.0,8.00,6
19,58,VTS,2013-01-13 10:26:00,2013-01-13 10:39:00,1,3.05,-73.947102,40.776297,1,NaN,-73.986542,40.766985,CRD,12.5,0.0,0.5,1.50,0.0,14.50,6
20,59,VTS,2013-01-13 10:34:00,2013-01-13 10:38:00,1,1.28,-74.000638,40.742342,1,NaN,-74.003445,40.732537,CRD,5.5,0.0,0.5,1.10,0.0,7.10,6
21,60,VTS,2013-01-13 10:24:00,2013-01-13 10:38:00,5,3.38,0.000000,0.000000,1,NaN,0.000000,0.000000,CRD,13.5,0.0,0.5,2.00,0.0,16.00,6
22,61,VTS,2013-01-13 10:22:00,2013-01-13 10:32:00,2,1.94,-73.985310,40.736002,1,NaN,-73.977813,40.755932,CRD,9.5,0.0,0.5,1.25,0.0,11.25,6
23,62,VTS,2013-01-13 10:27:00,2013-01-13 10:36:00,2,1.65,-73.981173,40.764808,1,NaN,-73.973818,40.782980,CRD,8.5,0.0,0.5,1.70,0.0,10.70,6
24,63,VTS,2013-01-13 10:24:00,2013-01-13 10:30:00,5,1.50,-73.968183,40.800170,1,NaN,-73.978958,40.785507,CRD,7.0,0.0,0.5,1.00,0.0,8.50,6
25,64,VTS,2013-01-13 10:28:00,2013-01-13 10:31:00,5,0.84,-73.979323,40.749270,1,NaN,-73.984082,40.741962,CSH,5.0,0.0,0.5,0.00,0.0,5.50,6
26,65,VTS,2013-01-13 10:20:00,2013-01-13 10:35:00,1,5.18,-73.942830,40.785677,1,NaN,-73.983460,40.737505,CRD,17.5,0.0,0.5,2.00,0.0,20.00,6
27,66,VTS,2013-01-13 10:13:00,2013-01-13 10:32:00,1,4.99,-74.002382,40.734097,1,NaN,-73.950875,40.771395,CRD,18.0,0.0,0.5,3.60,0.0,22.10,6
28,67,VTS,2013-01-13 10:19:00,2013-01-13 10:31:00,1,3.42,-73.947883,40.778640,1,NaN,-73.977798,40.756872,CSH,13.0,0.0,0.5,0.00,0.0,13.50,6
29,68,VTS,2013-01-13 10:21:00,2013-01-13 10:30:00,6,1.17,-73.990690,40.756355,1,NaN,-73.975457,40.755327,CSH,7.5,0.0,0.5,0.00,0.0,8.00,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1776404,14776585,VTS,2013-01-13 10:42:00,2013-01-13 10:47:00,6,1.69,-73.948248,40.770487,1,NaN,-73.968195,40.757157,CRD,7.0,0.0,0.5,1.40,0.0,8.90,6
1776405,14776586,VTS,2013-01-13 10:43:00,2013-01-13 10:47:00,6,0.77,-73.969697,40.748592,1,NaN,-73.969697,40.748592,CRD,5.0,0.0,0.5,2.00,0.0,7.50,6
1776406,14776587,VTS,2013-01-13 10:43:00,2013-01-13 10:49:00,6,1.05,0.000000,0.000000,1,NaN,0.000000,0.000000,CSH,6.5,0.0,0.5,0.00,0.0,7.00,6
1776407,14776588,VTS,2013-01-13 10:39:00,2013-01-13 10:50:00,1,2.52,-73.954485,40.783940,1,NaN,-73.982370,40.774832,CRD,10.5,0.0,0.5,1.50,0.0,12.50,6
1776408,14776589,VTS,2013-01-13 10:48:00,2013-01-13 10:51:00,1,1.05,0.000000,0.000000,1,NaN,0.000000,0.000000,CRD,5.0,0.0,0.5,1.00,0.0,6.50,6
1776409,14776590,VTS,2013-01-13 10:40:00,2013-01-13 10:48:00,1,1.59,-73.979012,40.785222,1,NaN,-73.956890,40.778587,CRD,8.0,0.0,0.5,1.00,0.0,9.50,6
1776410,14776591,VTS,2013-01-13 10:44:00,2013-01-13 10:53:00,1,1.81,-74.005890,40.736502,1,NaN,-73.990317,40.719637,CRD,9.0,0.0,0.5,1.00,0.0,10.50,6
1776411,14776592,VTS,2013-01-13 10:35:00,2013-01-13 10:48:00,1,6.74,-73.998595,40.713257,1,NaN,-73.950615,40.775147,CSH,19.5,0.0,0.5,0.00,0.0,20.00,6
1776412,14776593,VTS,2013-01-13 10:40:00,2013-01-13 10:48:00,1,2.03,-73.999880,40.733082,1,NaN,-73.977335,40.742120,CSH,9.0,0.0,0.5,0.00,0.0,9.50,6
1776413,14776594,VTS,2013-01-13 10:43:00,2013-01-13 10:51:00,1,2.52,-73.987382,40.732960,1,NaN,-73.972797,40.761817,CRD,9.5,0.0,0.5,1.00,0.0,11.00,6
1776414,14776595,VTS,2013-01-13 10:44:00,2013-01-13 10:49:00,1,1.38,-73.958648,40.780848,1,NaN,-73.965043,40.792803,CSH,6.0,0.0,0.5,0.00,0.0,6.50,6
1776415,14776596,VTS,2013-01-13 10:40:00,2013-01-13 10:47:00,6,1.78,-73.992230,40.725052,1,NaN,-73.992255,40.742875,CSH,8.0,0.0,0.5,0.00,0.0,8.50,6
1776416,14776597,VTS,2013-01-13 10:40:00,2013-01-13 10:50:00,1,2.70,-73.970332,40.752417,1,NaN,-73.993400,40.729155,CSH,10.5,0.0,0.5,0.00,0.0,11.00,6
1776417,14776598,VTS,2013-01-13 10:38:00,2013-01-13 10:50:00,2,2.84,-73.973782,40.793035,1,NaN,-73.960268,40.766312,CRD,11.0,0.0,0.5,1.00,0.0,12.50,6
1776418,14776599,VTS,2013-01-13 03:40:00,2013-01-13 03:44:00,3,0.62,-73.985535,40.747447,1,NaN,-73.980507,40.742447,CSH,4.5,0.5,0.5,0.00,0.0,5.50,6
1776419,14776600,VTS,2013-01-13 03:25:00,2013-01-13 03:42:00,5,4.54,-73.994112,40.720142,1,NaN,-73.961138,40.764202,CRD,16.0,0.5,0.5,2.20,0.0,19.20,6
1776420,14776601,VTS,2013-01-13 03:30:00,2013-01-13 03:42:00,1,3.24,-73.983567,40.743822,1,NaN,-74.006810,40.705607,CRD,12.5,0.5,0.5,3.25,0.0,16.75,6
1776421,14776602,VTS,2013-01-13 03:38:00,2013-01-13 03:42:00,1,0.76,-73.951655,40.725205,1,NaN,-73.955465,40.717912,CRD,4.5,0.5,0.5,0.00,0.0,5.50,6
1776422,14776603,VTS,2013-01-13 03:33:00,2013-01-13 03:40:00,1,2.02,-73.994750,40.720547,1,NaN,-73.988420,40.748812,CRD,8.0,0.5,0.5,1.70,0.0,10.70,6
1776423,14776604,VTS,2013-01-13 03:34:00,2013-01-13 03:40:00,1,0.84,-73.989377,40.726252,1,NaN,-73.980430,40.721872,CSH,5.5,0.5,0.5,0.00,0.0,6.50,6
1776424,14776605,VTS,2013-01-13 03:33:00,2013-01-13 03:45:00,5,1.87,-74.000530,40.730002,1,NaN,-73.976987,40.729015,CRD,10.0,0.5,0.5,2.10,0.0,13.10,6
1776425,14776606,VTS,2013-01-13 03:33:00,2013-01-13 03:47:00,2,2.39,-74.005355,40.740252,1,NaN,-73.980822,40.742002,CRD,11.5,0.5,0.5,2.40,0.0,14.90,6
1776426,14776607,VTS,2013-01-13 03:28:00,2013-01-13 03:45:00,1,4.57,-73.985747,40.726850,1,NaN,-73.982107,40.774395,CRD,17.0,0.5,0.5,3.50,0.0,21.50,6
1776427,14776608,VTS,2013-01-13 03:38:00,2013-01-13 03:45:00,1,0.90,-73.992625,40.727035,1,NaN,-74.003365,40.732437,CSH,6.5,0.5,0.5,0.00,0.0,7.50,6
1776428,14776609,VTS,2013-01-13 03:41:00,2013-01-13 03:46:00,1,0.97,-73.935070,40.750442,1,NaN,-73.926483,40.761665,CSH,6.0,0.5,0.5,0.00,0.0,7.00,6
1776429,14776610,VTS,2013-01-13 03:39:00,2013-01-13 03:46:00,1,1.53,-73.968997,40.755920,1,NaN,-73.987635,40.748973,CSH,7.5,0.5,0.5,0.00,0.0,8.50,6
1776430,14776611,VTS,2013-01-13 03:24:00,2013-01-13 03:45:00,1,3.47,-73.982642,40.723162,1,NaN,-73.954077,40.717237,CRD,16.5,0.5,0.5,2.00,0.0,19.50,6
1776431,14776612,VTS,2013-01-13 03:37:00,2013-01-13 03:45:00,6,2.10,-73.997530,40.721065,1,NaN,-73.983217,40.744395,CRD,9.0,0.5,0.5,1.90,0.0,11.90,6
1776432,14776613,VTS,2013-01-13 03:27:00,2013-01-13 03:45:00,1,6.88,-74.006972,40.743750,1,NaN,-73.913185,40.759290,CSH,21.0,0.5,0.5,0.00,0.0,22.00,6
1776433,14776614,VTS,2013-01-13 13:25:00,2013-01-13 13:29:00,3,0.78,-73.981802,40.768490,1,NaN,-73.981577,40.759860,CSH,5.0,0.0,0.5,0.00,0.0,5.50,6

In [94]:
print("Original shape is ", january2013.shape)
print("Monday's shape is ", january2013monday.shape)
print("Tuesday's shape is ", january2013tuesday.shape)
print("Wednesday's shape is ", january2013wednesday.shape)
print("Thursday's shape is ", january2013thursday.shape)
print("Friday's shape is ", january2013friday.shape)
print("Saturday's shape is ", january2013saturday.shape)
print("Sunday's shape is ", january2013sunday.shape)

Original shape is  (14776615, 19)
Monday's shape is  (1686416, 19)
Tuesday's shape is  (2324692, 19)
Wednesday's shape is  (2353435, 19)
Thursday's shape is  (2505915, 19)
Friday's shape is  (2080757, 19)
Saturday's shape is  (2048966, 19)
Sunday's shape is  (1776434, 19)

In [95]:
january2013.groupby('weekday').weekday.count()

weekday
0    1686416
1    2324692
2    2353435
3    2505915
4    2080757
5    2048966
6    1776434
Name: weekday, dtype: int64

In [97]:
january2013monday.head(2)

,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,rate_code,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,surcharge,mta_tax,tip_amount,tolls_amount,total_amount,weekday
3,CMT,2013-01-07 23:54:15,2013-01-07 23:58:20,2,0.7,-73.974600,40.759945,1,N,-73.984737,40.759388,CSH,5.0,0.5,0.5,0.0,0.0,6.0,0
4,CMT,2013-01-07 23:25:03,2013-01-07 23:34:24,1,2.1,-73.976252,40.748528,1,N,-74.002583,40.747867,CSH,9.5,0.5,0.5,0.0,0.0,10.5,0

In [99]:
january2013.groupby('tip_amount').tip_amount.count()

tip_amount
0.00      7236560
0.01         3403
0.02         1079
0.03          428
0.04          173
0.05          890
0.06          194
0.07          182
0.08          776
0.09          283
0.10         3638
0.11          269
0.12          128
0.13           22
0.14           21
0.15          811
0.16           17
0.17           20
0.18          127
0.19           19
0.20         1431
0.21           26
0.22          145
0.23           26
0.24            5
0.25          744
0.26            9
0.27           14
0.28           55
0.29           13
           ...
114.61          1
115.50          2
116.00          1
117.00          2
119.00          1
120.00          3
122.00          1
123.00          1
124.00          1
125.00          1
125.55          1
127.00          1
128.55          1
132.80          1
140.00          1
141.00          1
147.50          1
150.00          8
151.50          1
153.35          1
160.00          1
161.00          1
165.00          1
166.00          1
177.00          1
180.30          1
182.45          1
187.75          1
197.00          1
200.00          4
Name: tip_amount, dtype: int64